server:
  port: 9000

spring:
  datasource:
    url: jdbc:postgresql://htpc.lan:5431/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true

flyway:
  baselineOnMigrate:true

executor:
  default-limit: 10000
  reset-cron: 0 0 0 * * *