DROP TABLE IF EXISTS limits;
CREATE TABLE limits
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    amount NUMERIC(14,2),
    limit NUMERIC(14,2),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO limits(user_id, value) VALUES (1, 0, 10000);
INSERT INTO limits(user_id, value) VALUES (2, 0, 10000);
INSERT INTO limits(user_id, value) VALUES (3, 0, 10000);
INSERT INTO limits(user_id, value) VALUES (4, 0, 10000);
INSERT INTO limits(user_id, value) VALUES (5, 0, 10000);